In [1]:
import numpy as np

In [2]:
A = np.array([
    [0,1, 1, 0.0],
    [1,0,0,1],
    [1,0,0,1],
    [1,1,0,0]
])

In [4]:
print(np.dot(A,A))

[[2. 0. 0. 2.]
 [1. 2. 1. 0.]
 [1. 2. 1. 0.]
 [1. 1. 1. 1.]]


In [5]:
print(np.dot(A,np.dot(A,A)))

[[2. 4. 2. 0.]
 [3. 1. 1. 3.]
 [3. 1. 1. 3.]
 [3. 2. 1. 2.]]
