In [1]:
import copy
import numpy as np
from helperfunctions.timing import timeit
from IPython.core.debugger import set_trace

In [2]:
l1 = [1,2,3,4,5,6,7,8,9,10]
l2 = [10,9,8,7,6,5,4,3,2,1]
l3 = [2,5,6,4,4,4,1,2,4,10,5,7,9,2]
l4 = np.random.permutation(10000)
l5 = np.random.permutation(100000)

In [33]:
def naivesort(l):
    for i, e in enumerate(l):
        j = i
        while j>0 and e<l[j-1]:
            l[j] = l[j-1]
            j -= 1
        l[j] = e

@timeit(1)        
def timed_naivesort(l):
    naivesort(l)

In [10]:
naivesort(l2)
print(l2)
naivesort(l3)
print(l3)
naivesort(l4)
print(l4[0:10], l4[-10:])

average execution time: 1.50203704834e-05
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
average execution time: 1.38282775879e-05
[1, 2, 2, 2, 4, 4, 4, 4, 5, 5, 6, 7, 9, 10]
average execution time: 20.4616601467
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999]))


In [39]:
def swap(l, i, j):
    #tmp = copy.deepcopy(l[j])
    #l[j] = copy.deepcopy(l[i])
    tmp = l[j]
    l[j] = l[i]
    l[i] = tmp

In [40]:
@timeit(1)
def quicksort(l):
    quicksort_helper(l, 0, len(l)-1)

def quicksort_helper(l, starti, endi):
    #set_trace()
    if starti >= endi:
        return
    if endi-starti+1<=100:
        naivesort(l)
    else:
        middlei = int(0.5*(starti+endi))
        if (l[middlei]<l[starti]):
            swap(l,starti, middlei)
        if (l[endi]<l[starti]):
            swap(l, starti, endi)
        if (l[endi]<l[middlei]):
            swap(l, middlei, endi)
        pivoti = middlei
        
        swap(l, pivoti, endi-1)
        pivot = l[endi-1]
        lefti = starti+1
        righti = endi-2
        
        #print(lefti, righti, pivot)
        
        while True:
            while l[lefti]<pivot:
                lefti += 1
            while pivot<l[righti]:
                righti -= 1
            if lefti < righti:
                swap(l, lefti, righti)
            else:
                break
                
        pivoti = lefti
        swap(l, pivoti, endi-1)
        #print("call quicksort {}, {}".format(starti, pivoti-1))
        quicksort_helper(l, starti, pivoti-1)
        #print("call quicksort {}, {}".format(pivot+1, endi))
        quicksort_helper(l, pivoti+1, endi)

In [41]:
l1 = [1,2,3,4,5,6,7,8,9,10]
l2 = [10,9,8,7,6,5,4,3,2,1]
l3 = [2,5,6,4,4,4,1,2,4,10,5,7,9,2]
l4 = np.random.permutation(10000)
l5 = np.random.permutation(40000)

In [42]:
quicksort(l2)
print(l2)
quicksort(l3)
print(l3)
quicksort(l5)
print(l5[0:10], l5[-10:])

average execution time: 1.78813934326e-05
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
average execution time: 1.38282775879e-05
[1, 2, 2, 2, 4, 4, 4, 4, 5, 5, 6, 7, 9, 10]
average execution time: 140.315243006
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([39990, 39991, 39992, 39993, 39994, 39995, 39996, 39997, 39998,
       39999]))


In [22]:
assert sorted(copy.deepcopy(list(l4))) == list(l4)

In [38]:
timed_naivesort(l5)
print(l5[0:10], l5[-10:])

average execution time: 332.729719877
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([39990, 39991, 39992, 39993, 39994, 39995, 39996, 39997, 39998,
       39999]))
